### ISSUE TITLE
Increase bit width of the integer portion of the yaw values in the BFC

### ISSUE THREAD

**Issue by bcreeley** [Zclarkwilliams/Drone2_LS_Capstone#105]
We are having constant yaw without input from the receiver.  We increased the Kp of Yaw in the BFC to 40 and 44 and this seemed to overflow the s11.4 bit width.  This could be increased and then we could limit the output of the yaw portion of the PID to the Motor Mixer since the MM can only output a certain amount of granularity.

**Comment by Zclarkwilliams** [comment]
This was fixed when we expanded out calculation bit widths to 32 bits.
