### ISSUE TITLE
Change wire names of x/y/z_rotation and x/y/z_rotation_rate in drone2.v

### ISSUE THREAD

**Issue by bcreeley** [Zclarkwilliams/Drone2_LS_Capstone#51]
These wires should be renamed in drone2.v to more descriptive names, shown below.  These changes will need to be mirrored on the draw.io file "Software Block Diagram.html" once they are made to keep the documentation up to date.

roll_rotation
pitch_rotation
yaw_rotation

roll_rotation_rate
pitch_rotation_rate
yaw_rotation_rate

**Comment by Zclarkwilliams** [comment]
This was updated in the flight_mode_testing branch and will be up to standards once branch is merged.
