### ISSUE TITLE
Get all of the modules looking near identical in style and format

### ISSUE THREAD

**Issue by bcreeley** [Zclarkwilliams/Drone2_LS_Capstone#54]
We are pretty close but there are still some modules that are different than the defined style.  This is just part of making easier for the next team to pick up where we left off with minimal pain.

**Comment by Zclarkwilliams** [comment]
This was accomplished by Zack. All module title blocks and descriptions are formatted the same, except BNO055_driver, and the i2c modules.

**Comment by ethangrinnell78** [comment]
Hah, wait a minute. I saw you change stuff in my modules. It's not all
synced up now?



Ethan Grinnell
CCIE R&S #39723
Network Engineer
Office of Information Technology, Computing Infrastructure Services,
Networking
Portland State University
503-725-3205

**Comment by Zclarkwilliams** [comment]
I did make the title block where we have the drone2 and names all match but the descriptions are technically no in the format of 
* Inputs
* @input_a: description
* @input_b: description
* @input_c: description
*
* Outputs
* @output_a: description
* @output_b: description


It is close and does have descriptions but I did not reformat it to actually match the format of the others on the inputs and outputs part.
